### ISSUE TITLE
bugs during training

### ISSUE THREAD

**Issue by Ashespt** [JiwanChung/esper#4]
Thanks for your awesome work!  I was trying to reproduce ESPER and found  some typos in train/README.md.  Like,
`cd code`
 `python parse_coco.py`
should be
`cd code/extracts/`
`python parse_coco.py`

In the file parse_coco.py, the arg <root> should be passed to main function,
` exit(main(root, args.clip_model_type))`
instead of
` exit(main(args.clip_model_type))`

And, when training ESPER, it throwed
`File ".../esper/train/code/data.py", line 50, in __call__
    features = torch.stack(features, dim=0)
TypeError: expected Tensor as element 0 in argument 0, but got numpy.ndarray`

Is it the latest version of esper?  I would appreciate it if you could give more details.

**Comment by Ashespt** [comment]
Thanks for your work again. I fixed some bugs and it runs successfully now.

**Comment by JiwanChung** [comment]
Sorry for the late reply. Good to know that you solved the issue.
For additional details, we extract the CLIP features following CLIPCap (https://github.com/rmokady/CLIP_prefix_caption/blob/main/parse_coco.py). 

Also, thank you for reporting the typos. I'll update the code in time.

**Comment by Ashespt** [comment]
Thanks for your reply!

**Comment by saveriosciara** [comment]
Hello! I'm sorry to bother you, I was trying to reproduce ESPER and I found the same error reported by @Ashespt about the TypeError in the main.py
I would like to know how you resolved 
Thank you in advance!

**Comment by JiwanChung** [comment]
Hi @saveriosciara! I updated the code to fix the problems raised earlier. Can you check if the fix works for you as well?

**Comment by saveriosciara** [comment]
Hi @JiwanChung! Firstly, thank you for your reply and your awesome work
I tried this method before writing my previous comment, but the code exits with the following error:
 `Traceback (most recent call last):
  File "/content/esper/train/code/main.py", line 605, in <module>
    main()
  File "/content/esper/train/code/main.py", line 593, in main
    trainer.step(step_num)
  File "/content/esper/train/code/main.py", line 145, in step
    image_ids, input_ids, attention_mask, features, labels, _ = next(self.train_sampler)
ValueError: too many values to unpack (expected 6)`

I checked out but I couldn't find a solution
